//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_list
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee1
    {
        public int emp_id { get; set; }
        public Nullable<int> dept_id { get; set; }
        public Nullable<int> mngr_id { get; set; }
        public string emp_name { get; set; }
        public Nullable<decimal> salary { get; set; }
    }
}
